# Generated by Django 6.0.4 on 2026-04-17 20:03

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="YieldCurve",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "curve_type",
                    models.CharField(
                        choices=[
                            ("government", "Government"),
                            ("swap", "Swap"),
                            ("corporate", "Corporate"),
                            ("ois", "OIS"),
                        ],
                        default="government",
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "model",
                    models.CharField(
                        choices=[
                            ("nelson_siegel", "Nelson-Siegel"),
                            ("svensson", "Svensson"),
                            ("bootstrap", "Bootstrap"),
                            ("cubic_spline", "Cubic Spline"),
                        ],
                        default="nelson_siegel",
                        max_length=20,
                    ),
                ),
                ("as_of_date", models.DateField()),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("r_squared", models.FloatField(blank=True, null=True)),
                ("rmse", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Yield Curve",
                "verbose_name_plural": "Yield Curves",
                "ordering": ["-as_of_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["as_of_date"], name="curves_yiel_as_of_d_992a28_idx"
                    ),
                    models.Index(
                        fields=["curve_type"], name="curves_yiel_curve_t_f325f2_idx"
                    ),
                    models.Index(
                        fields=["currency"], name="curves_yiel_currenc_9d41cb_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CurveDataPoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tenor", models.FloatField(help_text="Tenor in years")),
                ("rate", models.FloatField(help_text="Par yield / rate as decimal")),
                ("instrument", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "curve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points",
                        to="curves.yieldcurve",
                    ),
                ),
            ],
            options={
                "verbose_name": "Curve Data Point",
                "ordering": ["tenor"],
                "unique_together": {("curve", "tenor")},
            },
        ),
    ]
