# Generated by Django 6.0.4 on 2026-04-17 20:03

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bond",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "isin",
                    models.CharField(
                        blank=True,
                        help_text="ISO 6166 ISIN (2-letter country code + 9 alphanumeric + check digit)",
                        max_length=12,
                        null=True,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("issuer", models.CharField(max_length=255)),
                (
                    "face_value",
                    models.DecimalField(
                        decimal_places=6,
                        default=1000.0,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(1e-06)],
                    ),
                ),
                (
                    "coupon_rate",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Annual coupon rate as decimal (e.g. 0.05 = 5%)",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("maturity_date", models.DateField()),
                ("issue_date", models.DateField()),
                ("settlement_date", models.DateField(blank=True, null=True)),
                (
                    "coupon_frequency",
                    models.CharField(
                        choices=[
                            ("annual", "Annual"),
                            ("semiannual", "Semi-Annual"),
                            ("quarterly", "Quarterly"),
                            ("monthly", "Monthly"),
                            ("zero", "Zero (Discount)"),
                        ],
                        default="semiannual",
                        max_length=20,
                    ),
                ),
                (
                    "bond_type",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed Rate"),
                            ("floating", "Floating Rate"),
                            ("zero_coupon", "Zero Coupon"),
                            ("inflation_linked", "Inflation Linked"),
                            ("callable", "Callable"),
                        ],
                        default="fixed",
                        max_length=20,
                    ),
                ),
                (
                    "day_count",
                    models.CharField(
                        choices=[
                            ("actual/actual", "Actual/Actual"),
                            ("actual/360", "Actual/360"),
                            ("actual/365", "Actual/365"),
                            ("30/360", "30/360"),
                        ],
                        default="actual/actual",
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "credit_rating",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("sector", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Bond",
                "verbose_name_plural": "Bonds",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["issuer"], name="bonds_bond_issuer_a71470_idx"
                    ),
                    models.Index(
                        fields=["bond_type"], name="bonds_bond_bond_ty_44651e_idx"
                    ),
                    models.Index(
                        fields=["sector"], name="bonds_bond_sector_26f983_idx"
                    ),
                    models.Index(
                        fields=["credit_rating"], name="bonds_bond_credit__b0d812_idx"
                    ),
                    models.Index(
                        fields=["currency"], name="bonds_bond_currenc_9336be_idx"
                    ),
                    models.Index(
                        fields=["maturity_date"], name="bonds_bond_maturit_47abdf_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CallSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("call_date", models.DateField()),
                (
                    "call_price",
                    models.DecimalField(
                        decimal_places=4,
                        default=100.0,
                        help_text="Call price as percentage of face value (e.g. 102.0 = 102%)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.0001)],
                    ),
                ),
                (
                    "bond",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="call_schedule",
                        to="bonds.bond",
                    ),
                ),
            ],
            options={
                "verbose_name": "Call Schedule Entry",
                "verbose_name_plural": "Call Schedule",
                "ordering": ["call_date"],
                "unique_together": {("bond", "call_date")},
            },
        ),
    ]
